### ISSUE TITLE
Trouble retrieving text

### ISSUE THREAD

**Issue by alokgrover** [55minutes/python-epo-ops-client#12]
Hi, 

First, thank you for creating this package. I am a beginner when it comes to using API. I am trying to extract data but not receiving any text. 

I ran this code:

mport epo_ops

anonymous_client = epo_ops.Client()  # Instantiate a default client
response = anonymous_client.published_data(  # Retrieve bibliography data
  reference_type = 'publication',  # publication, application, priority
  input = epo_ops.models.Docdb('1000000', 'EP', 'A1'),  # original, docdb, epodoc
  endpoint = 'biblio',  # optional, defaults to biblio in case of published_data
  constituents = []  # optional, list of constituents
)

registered_client = epo_ops.RegisteredClient(key='abc', secret='xyz')
registered_client.access_token  # To see the current token
response = registered_client.published_data(…) 

# Replaced the last line: 
response = registered_client.published_data('publication', epo_ops.models.Docdb('1000000', 'EP', 'A1'), endpoint='biblio', constituents=None)

Output I got : <Response [200]>

How should I modify the code to retrieve text?  I would appreciate your help.

**Comment by eltermann** [comment]
Hi @alokgrover,

"response" variable is an object and you have to check "response.content" attribute for downloaded data

**Comment by gsong** [comment]
@alokgrover See <http://docs.python-requests.org/en/master/user/quickstart/#response-content> and <http://docs.python-requests.org/en/master/api/#requests.Response> for more information on the response object.
