### ISSUE TITLE
Update to OPS v3.2

### ISSUE THREAD

**Issue by eltermann** [55minutes/python-epo-ops-client#13]
From announcement [1]:

> The planned schedule is as follows:
> 
> •	Current: version 3.1 production environment – version 3.2 public beta
> •	January 2017: version 3.2 in full production – version 3.1 still available
> •	As from Q2 2017: **discontinuation of version 3.1**

@gsong, do you have any availability to coordinate this effort?

[1] http://forums.epo.org/open-patent-services-and-publication-server-web-service/topic5378.html

**Comment by gsong** [comment]
@eltermann I see you've started a branch to work on this. Keep me posted on your progress. I most likely won't look at this until January.

**Comment by dablak** [comment]
Hi, is there any progress? I can help if needed.

**Comment by gsong** [comment]
@dablak I haven't had a chance to look at this yet. If you want to fork and get started, that would be great. I haven't looked to see if there are major changes or not (hopefully not).

**Comment by eltermann** [comment]
I just changed the version number and it is already working for my use cases.

A careful look of API changes is still necessary though.

**Comment by gsong** [comment]
@eltermann Yeah, previous updates haven't required any changes in the code base, but I agree, someone should review the OPS change log to see if there's anything we need to worry about.

**Comment by gsong** [comment]
FYI, we'll be starting the work on this shortly.

**Comment by dablak** [comment]
We've been using the 3.2 endpoint for almost 3 months and it has been working fine for our uses cases so far.

**Comment by gsong** [comment]
@dablak I assume you mean just change the URL for this package? If so, good data point to know.

**Comment by dablak** [comment]
Yes, simply changing the URL

**Comment by eltermann** [comment]
From the announcement, support to anonymous client is discontinued in v3.2.

I'm removing "RegisteredClient" and making "Client" the only one available.

**Comment by gsong** [comment]
@eltermann Do you want to submit a PR?

/cc @emyller

**Comment by eltermann** [comment]
Just did it.

**Comment by gsong** [comment]
@eltermann 🙏

**Comment by emyller** [comment]
@gsong Just caught up. So I checked out @eltermann's work against the key changes in OPS 3.2; the [pull request](https://github.com/55minutes/python-epo-ops-client/pull/14) looks impeccable to me. :+1:
