### ISSUE TITLE
epo_ops.middlewares.Dogpile() module 'epo_ops.middlewares' has no attribute 'Dogpile'

### ISSUE THREAD

**Issue by joseberlines** [55minutes/python-epo-ops-client#30]
when running:
 middlewares = [
    epo_ops.middlewares.Dogpile(),
    epo_ops.middlewares.Throttler(),
]
I get:
'epo_ops.middlewares' has no attribute 'Dogpile'

I checked the dir of epo_ops.middlewares
print(dir(epo_ops.middlewares))

result:
['Middleware', 'Throttler', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'middleware', 'throttle']

'Throttler' is there but not 'Dogpile'.

Is everything all right?

**Comment by amotl** [comment]
Dear Jose,

as the [dogpile.cache](https://pypi.org/project/dogpile.cache/) package isn't part of the [requirements](https://github.com/55minutes/python-epo-ops-client/blob/v2.3.2/setup.py#L19) and is getting [silently ignored](https://github.com/55minutes/python-epo-ops-client/blob/v2.3.2/epo_ops/middlewares/__init__.py#L6-L9) when trying to import the corresponding module (including turtles all the way down), you might be successful by just typing out
```
pip install dogpile.cache
```

Cheers,
Andreas.

**Comment by gsong** [comment]
@joseberlines I hope @amotl's hint provided you with a solution. Caching is optional so isn't installed by default.
