### ISSUE TITLE
Constantly get 404 error

### ISSUE THREAD

**Issue by MauritiusJJK** [55minutes/python-epo-ops-client#31]
Hello! 
I using the EPO OPS client but have some troubles with my request.
When I use the example request of the EPO OPS client everything seems to work fine, but when using my code i constantly get a 404 error. 
HTTPError: 404 Client Error: Not Found for url: https://ops.epo.org/3.2/rest-services/register/application/epodoc/biblio
Seems like between /epodoc and /biblio the application number seems to be missing right?
This is my code:

```
#example
	client = epo_ops.Client(key='key', secret='secret')  # Instantiate client
        response = client.register(  # Retrieve bibliography data
		  		reference_type = 'application',  # publication, application, priority
		  		input = epo_ops.models.Epodoc('12345'),  # original, docdb, epodoc
		  		constituents = ['biblio']  # optional, list of constituents
				)
```
I tried to do i similar like in the example
input = epo_ops.models.Docdb('1000000', 'EP', 'A1'),
but using
input = epo_ops.models.Epodoc(appnum), instead, as i want to make a register request.

https://www.pydoc.io/pypi/python-epo-ops-client-2.3.0/autoapi/models/index.html says that models.Epodoc just needs a number as input.
Does anyone know what i misunderstood or what is going wrong?

**Comment by gsong** [comment]
@MauritiusJJK If you're getting a 404, that means the EPODOC number you supplied cannot be found by OPS. You can use https://worldwide.espacenet.com/singleLineSearch?locale=en_EP to see if you can find the number you're looking for. If you can, then post back and we'll figure it out.
