### ISSUE TITLE
TypeError: _make_request() got an unexpected keyword argument 'use_get'

### ISSUE THREAD

**Issue by amotl** [55minutes/python-epo-ops-client#35]
Dear @gsong,

first things first: Thanks again for your exceptional work on maintaining this library.

We just tried to integrate the most recent release `python-epo-ops-client 3.1.1` into [PatZilla](https://github.com/ip-tools/ip-navigator) as we are looking forward to the updates coming from #33 and #34.

However, we hit a speed bump we would like to share with you. When requesting family information, `python_epo_ops_client-3.1.1` croaked like

```python
  File "/Users/amo/dev/elmyra/sources/ip-navigator/patzilla/access/epo/ops/api.py", line 718, in ops_family_inpadoc
    response = ops.family(reference_type, ops_id, constituents=to_list(constituents))
  File "/Users/amo/dev/elmyra/sources/ip-navigator/.venv2/lib/python2.7/site-packages/python_epo_ops_client-3.1.1-py2.7.egg/epo_ops/api.py", line 50, in family
    return self._make_request(url, None, params=input.as_api_input(), use_get=True)
TypeError: _make_request() got an unexpected keyword argument 'use_get'
```

While we haven't investigated this more thoroughly, it looks like the problem is coming from within the module.

Thanks already for looking into this and with kind regards,
Andreas.

**Comment by gsong** [comment]
Will check this out shortly.

**Comment by amotl** [comment]
Thanks!

**Comment by gsong** [comment]
@amotl Hmm, I couldn't reproduce this:

```
In [20]: from epo_ops import Client

In [21]: from epo_ops.models import Docdb

In [22]: c = Client('key', 'secret')

In [23]: response = c.family("publication", Docdb("1000000", "EP", "A1"), constituents=['biblio
    ...: ', 'legal'])

In [24]: response.status_code
Out[24]: 200
```

Does that match your expectation?

**Comment by amotl** [comment]
Thanks, I will check this again.

**Comment by amotl** [comment]
After pulling the most recent changes from `development`, I can confirm all tests are succeeding
```
pytest -s -v --cov-report term --cov epo_ops tests
```

especially the tests added to cover the topic #33 and #34.
```
tests/test_api.py::test_family[default_client] PASSED
tests/test_api.py::test_family_biblio[default_client] PASSED
tests/test_api.py::test_family_legal[default_client] PASSED
```

So, I am puzzled why PatZilla would croak on that. Investigating...

---

However, those two guys fail
```
tests/test_ops_quota.py::test_mock_quota_exceeded[cached_client] FAILED
tests/test_ops_quota.py::test_mock_quota_exceeded[default_client] FAILED
```

which is totally unrelated to this issue, so this is just FYI.

**Comment by gsong** [comment]
@amotl In order to successfully execute the mock tests, you'll need to get a apiary URL as specified in https://github.com/55minutes/python-epo-ops-client#tests.

**Comment by gsong** [comment]
You can always refer to [travis](https://travis-ci.org/55minutes/python-epo-ops-client) as well.

**Comment by amotl** [comment]
> In order to successfully execute the mock tests, you'll need to get an apiary URL

I see, thanks. I was running them against production by using `export APIARY_URL=https://ops.epo.org/`.

**Comment by gsong** [comment]
@amotl Can you try `APIARY_URL=http://private-anon-111333769e-opsv31.apiary-mock.com`?

**Comment by amotl** [comment]
That works perfectly and also makes the mock tests pass. Thanks!

**Comment by gsong** [comment]
@amotl Only the EPO failure cases (quota exceeded per day/week) hit the mock API url, as there's no way to simulate that directly at OPS (they don't have a staging server with failure simulation URLs, as far as I know). Everything else hits the actual OPS end points, that's why the OPS key and secret is required for testing.

**Comment by gsong** [comment]
You can see what Apiary mocks: https://opsv31.docs.apiary.io/.

Also thanks for testing, I'll document the anonymous URL in the project docs.

**Comment by amotl** [comment]
> Only the EPO failure cases (quota exceeded per day/week) hit the mock API url.

Thank you very much for letting us know about this important detail. So, there's no reason not to run the tests against the Apiary endpoint.

**Comment by amotl** [comment]
Regarding the `TypeError`, we just have been able to find out about the root cause. It was totally our fault, as we have been bitten by a custom routine monkeypatching the `_make_request` method of `epo-ops-client` [1]. Oh my! ;]

If you are curious, the only thing we changed to that method is that we didn't want to invoke `raise_for_status()`.
```
# Let errors propagate. Don't croak on anything status >= 400.
#response.raise_for_status()
```

[1] https://github.com/ip-tools/ip-navigator/blob/6f35752e128f0c3138a306d8bce75199c0808cd6/patzilla/access/epo/ops/client.py#L105-L127

**Comment by gsong** [comment]
@amotl Feel free to file an enhancement issue and I can think about how best to allow that behavior to be toggle-able.

**Comment by amotl** [comment]
Thanks again!
