### ISSUE TITLE
Module epo_ops not found

### ISSUE THREAD

**Issue by Pankajgargrwire** [55minutes/python-epo-ops-client#37]
I ran the following basic code for OPS authentication using my API keys. Code looks like below

import epo_ops

client = epo_ops.Client(key='Key1', secret='Seckey1')  # Instantiate client
response = client.published_data(  # Retrieve bibliography data
reference_type = 'publication',  # publication, application, priority
input = epo_ops.models.Docdb('1000000', 'EP', 'A1'),  # original, docdb, epodoc
endpoint = 'biblio',  # optional, defaults to biblio in case of published_data
constituents = []  # optional, list of constituents
)

When I ran, it showed ImportError: No module named epo_ops. Fixes I have tried so far
1. pip install epo_ops 
2. Downloaded zip file from GitHub and ran the setup file but still it did not recognized epo_ops.

**Comment by amotl** [comment]
Hi there,

the canonical package name is `python-epo-ops-client`. So, that should work:
```
pip install python-epo-ops-client
```

With kind regards,
Andreas.

**Comment by gsong** [comment]
@Pankajgargrwire Let us know if that worked for you.

**Comment by Pankajgargrwire** [comment]
It worked for me. Thanks a lot !!
